version: '3.9'

services:
  vue:
    build: .
    container_name: demo
    restart: always
    networks: 
      - pn 
    environment:
      NODE_ENV: production
      VUE_APP_DEMO: https://demo.ikaveh.com
    ports:
      - 80:80
    # command: 
    #   "npm run start"
networks:
  pn:
    external: 
      name: private-network